apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-04T05:00:42Z"
  name: simplenode-canary
  resourceVersion: "98335"
  selfLink: /api/v1/namespaces/simpleproject-production/services/simplenode
  uid: 4b7158dd-470b-11ea-96d4-42010aa80003
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
