apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-04T03:46:15Z"
  name: simplenode-primary
  resourceVersion: "81441"
  selfLink: /api/v1/namespaces/simpleproject-staging/services/simplenode
  uid: e52fffee-4700-11ea-96d4-42010aa80003
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
